INSERT INTO FP_DOC_TYPE_T (FDOC_TYP_CD,VER_NBR,FDOC_NM,FDOC_TYP_ACTIVE_CD,OBJ_ID)
VALUES('ICPR', 1, 'IACUC Protocol', 'Y', SYS_GUID())
/
INSERT INTO SPECIAL_REVIEW_USAGE (SPECIAL_REVIEW_USAGE_ID,SPECIAL_REVIEW_CODE,MODULE_CODE,ACTIVE_FLAG,UPDATE_TIMESTAMP,UPDATE_USER,VER_NBR,OBJ_ID,GLOBAL_FLAG)
VALUES (66, 1, (SELECT MODULE_CODE FROM COEUS_MODULE WHERE DESCRIPTION='IACUC Protocol'), 'Y', SYSDATE, 'admin', 1, SYS_GUID(), 'Y')
/
INSERT INTO SPECIAL_REVIEW_USAGE (SPECIAL_REVIEW_USAGE_ID,SPECIAL_REVIEW_CODE,MODULE_CODE,ACTIVE_FLAG,UPDATE_TIMESTAMP,UPDATE_USER,VER_NBR,OBJ_ID,GLOBAL_FLAG)
VALUES (67, 2, (SELECT MODULE_CODE FROM COEUS_MODULE WHERE DESCRIPTION='IACUC Protocol'), 'Y', SYSDATE, 'admin', 1, SYS_GUID(), 'Y')
/
INSERT INTO SPECIAL_REVIEW_USAGE (SPECIAL_REVIEW_USAGE_ID,SPECIAL_REVIEW_CODE,MODULE_CODE,ACTIVE_FLAG,UPDATE_TIMESTAMP,UPDATE_USER,VER_NBR,OBJ_ID,GLOBAL_FLAG)
VALUES (68, 3, (SELECT MODULE_CODE FROM COEUS_MODULE WHERE DESCRIPTION='IACUC Protocol'), 'Y', SYSDATE, 'admin', 1, SYS_GUID(), 'Y')
/
INSERT INTO SPECIAL_REVIEW_USAGE (SPECIAL_REVIEW_USAGE_ID,SPECIAL_REVIEW_CODE,MODULE_CODE,ACTIVE_FLAG,UPDATE_TIMESTAMP,UPDATE_USER,VER_NBR,OBJ_ID,GLOBAL_FLAG)
VALUES (69, 4, (SELECT MODULE_CODE FROM COEUS_MODULE WHERE DESCRIPTION='IACUC Protocol'), 'Y', SYSDATE, 'admin', 1, SYS_GUID(), 'Y')
/
INSERT INTO SPECIAL_REVIEW_USAGE (SPECIAL_REVIEW_USAGE_ID,SPECIAL_REVIEW_CODE,MODULE_CODE,ACTIVE_FLAG,UPDATE_TIMESTAMP,UPDATE_USER,VER_NBR,OBJ_ID,GLOBAL_FLAG)
VALUES (70, 5, (SELECT MODULE_CODE FROM COEUS_MODULE WHERE DESCRIPTION='IACUC Protocol'), 'Y', SYSDATE, 'admin', 1, SYS_GUID(), 'Y')
/
INSERT INTO SPECIAL_REVIEW_USAGE (SPECIAL_REVIEW_USAGE_ID,SPECIAL_REVIEW_CODE,MODULE_CODE,ACTIVE_FLAG,UPDATE_TIMESTAMP,UPDATE_USER,VER_NBR,OBJ_ID,GLOBAL_FLAG)
VALUES (71, 6, (SELECT MODULE_CODE FROM COEUS_MODULE WHERE DESCRIPTION='IACUC Protocol'), 'Y', SYSDATE, 'admin', 1, SYS_GUID(), 'Y')
/
INSERT INTO SPECIAL_REVIEW_USAGE (SPECIAL_REVIEW_USAGE_ID,SPECIAL_REVIEW_CODE,MODULE_CODE,ACTIVE_FLAG,UPDATE_TIMESTAMP,UPDATE_USER,VER_NBR,OBJ_ID,GLOBAL_FLAG)
VALUES (72, 7, (SELECT MODULE_CODE FROM COEUS_MODULE WHERE DESCRIPTION='IACUC Protocol'), 'Y', SYSDATE, 'admin', 1, SYS_GUID(), 'Y')
/
INSERT INTO SPECIAL_REVIEW_USAGE (SPECIAL_REVIEW_USAGE_ID,SPECIAL_REVIEW_CODE,MODULE_CODE,ACTIVE_FLAG,UPDATE_TIMESTAMP,UPDATE_USER,VER_NBR,OBJ_ID,GLOBAL_FLAG)
VALUES (73, 8, (SELECT MODULE_CODE FROM COEUS_MODULE WHERE DESCRIPTION='IACUC Protocol'), 'Y', SYSDATE, 'admin', 1, SYS_GUID(), 'Y')
/
INSERT INTO SPECIAL_REVIEW_USAGE (SPECIAL_REVIEW_USAGE_ID,SPECIAL_REVIEW_CODE,MODULE_CODE,ACTIVE_FLAG,UPDATE_TIMESTAMP,UPDATE_USER,VER_NBR,OBJ_ID,GLOBAL_FLAG)
VALUES (74, 9, (SELECT MODULE_CODE FROM COEUS_MODULE WHERE DESCRIPTION='IACUC Protocol'), 'Y', SYSDATE, 'admin', 1, SYS_GUID(), 'Y')
/
INSERT INTO SPECIAL_REVIEW_USAGE (SPECIAL_REVIEW_USAGE_ID,SPECIAL_REVIEW_CODE,MODULE_CODE,ACTIVE_FLAG,UPDATE_TIMESTAMP,UPDATE_USER,VER_NBR,OBJ_ID,GLOBAL_FLAG)
VALUES (75,10, (SELECT MODULE_CODE FROM COEUS_MODULE WHERE DESCRIPTION='IACUC Protocol'), 'Y', SYSDATE, 'admin', 1, SYS_GUID(), 'Y')
/
INSERT INTO SPECIAL_REVIEW_USAGE (SPECIAL_REVIEW_USAGE_ID,SPECIAL_REVIEW_CODE,MODULE_CODE,ACTIVE_FLAG,UPDATE_TIMESTAMP,UPDATE_USER,VER_NBR,OBJ_ID,GLOBAL_FLAG)
VALUES (76,11, (SELECT MODULE_CODE FROM COEUS_MODULE WHERE DESCRIPTION='IACUC Protocol'), 'Y', SYSDATE, 'admin', 1, SYS_GUID(), 'Y')
/
INSERT INTO SPECIAL_REVIEW_USAGE (SPECIAL_REVIEW_USAGE_ID,SPECIAL_REVIEW_CODE,MODULE_CODE,ACTIVE_FLAG,UPDATE_TIMESTAMP,UPDATE_USER,VER_NBR,OBJ_ID,GLOBAL_FLAG)
VALUES (77,12, (SELECT MODULE_CODE FROM COEUS_MODULE WHERE DESCRIPTION='IACUC Protocol'), 'Y', SYSDATE, 'admin', 1, SYS_GUID(), 'Y')
/
